/*     ___    ____  __    ___   _________
 *    /   |  / _  |/ /   / / | / /__  __/          Source Code Static Analyzer
 *   / /| | / / / / /   / /  |/ /  / /                  AdLint - Advanced Lint
 *  / __  |/ /_/ / /___/ / /|  /  / /
 * /_/  |_|_____/_____/_/_/ |_/  /_/  Copyright (C) 2010-2014, OGIS-RI Co.,Ltd.
 *
 * Compiler specific initial header file generated by adlintize 3.2.14
 * at 2018-10-08 11:14:43 +0200.
 */

/* Put compiler specific predefined macros and types here. */
